name: ECMWF_temperture
on:
  workflow_dispatch:
  schedule:
  #1日2回、UTC 7:00AMと7:00PM(日本時間4:00PMと4:00AM)に実行
    - cron: '0 7,19 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # This fetches all history so you can handle merges if needed
      
      # Set up Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install necessary Python packages
        run: pip install ecmwf-data ecmwf-opendata magpye datetime lxml pygrib basemap
        
      - name: Run ECMWF_temperture script
        run: python ECMWF_temperture.py
      
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
