#熱中症による救急搬送者を取得する
name: heatstroke
on:
  workflow_dispatch:
  schedule:
  #UTC10時(日本時間の19時)に実行
  #更新は週１回（火曜）だが、発表日がずれる可能性もあるので
    - cron: '0 10 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      # Set up Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install necessary Python packages
        run: pip install pandas beautifulsoup4 requests tabula-py
      - name: Run heatstroke script
        run: python heatstroke.py
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
