#02-気象庁、最高気温の最新データを毎時取得
#集計①真夏日・猛暑日の観測地点数（全国）最新＋過去データと統合
#集計②都道府県別の最高気温　最新＋過去データと統合
#集計③各観測地点の「きょうの最高気温」　最新データに更新

#最新データは1時間毎の更新（毎時00分の観測データを50分過ぎに更新）
###過去７日はウェブ上のデータは毎日5:00ごろ更新＋修正は13:00、19:00、翌日1:00ごろの更新で反映
###→github上で30分遅れで取得しているものを呼び出す
#定期実行
name: jma-maxtemp-02-get-data-latest

on:
  workflow_dispatch:
  schedule:
    #1時間おきに実行
    - cron: '0 * * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install necessary Python packages
        run: pip install pandas
        
      - name: Run jma-maxtemp-02-get-data-latest script
        run: python jma-maxtemp-02-get-data-latest.py
        
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
