#環境省「暑さ指数」の地図用データ更新
##1. 元データは毎時30分ごろ更新
##2. Google Sheetは毎時40分にデータ取得
##3. 本コードは毎時50分ごろ運転
##データ取得の流れ：元データ→いったんGoogle sheetにとりこむ→pythonで読む
##環境省のサーバー設定が要因でgithub actionsではSSLセキュリティでエラーになるため

name: wbgt

on:
  workflow_dispatch:
  schedule:
      #UTC5:30分ごとに実行
      #- cron: '*/60 * * * *'
  #毎時50分に実行
    - cron: '50 * * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install necessary Python packages
        run: pip install pandas requests
        
      - name: Run wbgt script
        run: python wbgt.py
        
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
